version: "3.9"

services:
  backend:
    build: ./ktg-monitor
    container_name: ktg-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend/models:/app/models

  frontend:
    build: ./fetal-monitor-spa
    container_name: ktg-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
